/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class A */

#ifndef _Included_A
#define _Included_A
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     A
 * Method:    hindsightInit
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_A_hindsightInit
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     A
 * Method:    hindsightTracepoint
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_A_hindsightTracepoint
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     A
 * Method:    hindsightBegin
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_A_hindsightBegin
  (JNIEnv *, jclass, jlong);

/*
 * Class:     A
 * Method:    hindsightEnd
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_A_hindsightEnd
  (JNIEnv *, jclass);

/*
 * Class:     A
 * Method:    test
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_A_test
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
