/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class A */

#ifndef _Included_A
#define _Included_A
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     A
 * Method:    hindsightInit
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_A_hindsightInit
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     A
 * Method:    test
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_A_test
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
