/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HindsightJNI */

#ifndef _Included_HindsightJNI
#define _Included_HindsightJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HindsightJNI
 * Method:    hindsightInit
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_HindsightJNI_hindsightInit
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     HindsightJNI
 * Method:    hindsightTracepoint
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_HindsightJNI_hindsightTracepoint
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     HindsightJNI
 * Method:    hindsightBegin
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_HindsightJNI_hindsightBegin
  (JNIEnv *, jclass, jlong);

/*
 * Class:     HindsightJNI
 * Method:    hindsightEnd
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HindsightJNI_hindsightEnd
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
