/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HindsightJNI */

#ifndef _Included_HindsightJNI
#define _Included_HindsightJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HindsightJNI
 * Method:    hindsightInit
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_HindsightJNI_hindsightInit
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     HindsightJNI
 * Method:    hindsightBegin
 * Signature: (J)LHindsightJNI/Trace;
 */
JNIEXPORT jobject JNICALL Java_HindsightJNI_hindsightBegin
  (JNIEnv *, jclass, jlong);

/*
 * Class:     HindsightJNI
 * Method:    returnBufferNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HindsightJNI_returnBufferNative
  (JNIEnv *, jclass);

/*
 * Class:     HindsightJNI
 * Method:    switchBufferNative
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_HindsightJNI_switchBufferNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
