/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HindSightJNI */

#ifndef _Included_HindSightJNI
#define _Included_HindSightJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HindSightJNI
 * Method:    hindsightInit
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_HindSightJNI_hindsightInit
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     HindSightJNI
 * Method:    hindsightTracepoint
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_HindSightJNI_hindsightTracepoint
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     HindSightJNI
 * Method:    hindsightBegin
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_HindSightJNI_hindsightBegin
  (JNIEnv *, jclass, jlong);

/*
 * Class:     HindSightJNI
 * Method:    hindsightEnd
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HindSightJNI_hindsightEnd
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
