// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        (unknown)
// source: datapb.proto

package datapb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type RequestID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rid []int64 `protobuf:"varint,1,rep,packed,name=rid,proto3" json:"rid,omitempty"`
}

func (x *RequestID) Reset() {
	*x = RequestID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datapb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestID) ProtoMessage() {}

func (x *RequestID) ProtoReflect() protoreflect.Message {
	mi := &file_datapb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestID.ProtoReflect.Descriptor instead.
func (*RequestID) Descriptor() ([]byte, []int) {
	return file_datapb_proto_rawDescGZIP(), []int{0}
}

func (x *RequestID) GetRid() []int64 {
	if x != nil {
		return x.Rid
	}
	return nil
}

type Trace struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId int64    `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Entry     []int32  `protobuf:"varint,2,rep,packed,name=entry,proto3" json:"entry,omitempty"`
	Trace     []byte   `protobuf:"bytes,3,opt,name=trace,proto3" json:"trace,omitempty"`
	Addrs     []string `protobuf:"bytes,4,rep,name=addrs,proto3" json:"addrs,omitempty"`
}

func (x *Trace) Reset() {
	*x = Trace{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datapb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Trace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trace) ProtoMessage() {}

func (x *Trace) ProtoReflect() protoreflect.Message {
	mi := &file_datapb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trace.ProtoReflect.Descriptor instead.
func (*Trace) Descriptor() ([]byte, []int) {
	return file_datapb_proto_rawDescGZIP(), []int{1}
}

func (x *Trace) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *Trace) GetEntry() []int32 {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *Trace) GetTrace() []byte {
	if x != nil {
		return x.Trace
	}
	return nil
}

func (x *Trace) GetAddrs() []string {
	if x != nil {
		return x.Addrs
	}
	return nil
}

type CallRet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Callret bool `protobuf:"varint,1,opt,name=callret,proto3" json:"callret,omitempty"`
}

func (x *CallRet) Reset() {
	*x = CallRet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datapb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallRet) ProtoMessage() {}

func (x *CallRet) ProtoReflect() protoreflect.Message {
	mi := &file_datapb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallRet.ProtoReflect.Descriptor instead.
func (*CallRet) Descriptor() ([]byte, []int) {
	return file_datapb_proto_rawDescGZIP(), []int{2}
}

func (x *CallRet) GetCallret() bool {
	if x != nil {
		return x.Callret
	}
	return false
}

var File_datapb_proto protoreflect.FileDescriptor

var file_datapb_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x64, 0x61, 0x74, 0x61, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x64, 0x61, 0x74, 0x61, 0x70, 0x62, 0x22, 0x1d, 0x0a, 0x09, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03,
	0x52, 0x03, 0x72, 0x69, 0x64, 0x22, 0x68, 0x0a, 0x05, 0x54, 0x72, 0x61, 0x63, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x05, 0x65, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x72, 0x61, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x05, 0x74, 0x72, 0x61, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x64, 0x64,
	0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x61, 0x64, 0x64, 0x72, 0x73, 0x22,
	0x23, 0x0a, 0x07, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x61,
	0x6c, 0x6c, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x63, 0x61, 0x6c,
	0x6c, 0x72, 0x65, 0x74, 0x32, 0x38, 0x0a, 0x05, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x2f, 0x0a,
	0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x11, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x70,
	0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x44, 0x1a, 0x0f, 0x2e, 0x64, 0x61,
	0x74, 0x61, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x74, 0x22, 0x00, 0x32, 0x37,
	0x0a, 0x09, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x2a, 0x0a, 0x06, 0x52,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x0d, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x70, 0x62, 0x2e, 0x54,
	0x72, 0x61, 0x63, 0x65, 0x1a, 0x0f, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x70, 0x62, 0x2e, 0x43, 0x61,
	0x6c, 0x6c, 0x52, 0x65, 0x74, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2f, 0x64, 0x61, 0x74, 0x61,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_datapb_proto_rawDescOnce sync.Once
	file_datapb_proto_rawDescData = file_datapb_proto_rawDesc
)

func file_datapb_proto_rawDescGZIP() []byte {
	file_datapb_proto_rawDescOnce.Do(func() {
		file_datapb_proto_rawDescData = protoimpl.X.CompressGZIP(file_datapb_proto_rawDescData)
	})
	return file_datapb_proto_rawDescData
}

var file_datapb_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_datapb_proto_goTypes = []interface{}{
	(*RequestID)(nil), // 0: datapb.RequestID
	(*Trace)(nil),     // 1: datapb.Trace
	(*CallRet)(nil),   // 2: datapb.CallRet
}
var file_datapb_proto_depIdxs = []int32{
	0, // 0: datapb.Agent.Request:input_type -> datapb.RequestID
	1, // 1: datapb.Collector.Report:input_type -> datapb.Trace
	2, // 2: datapb.Agent.Request:output_type -> datapb.CallRet
	2, // 3: datapb.Collector.Report:output_type -> datapb.CallRet
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_datapb_proto_init() }
func file_datapb_proto_init() {
	if File_datapb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_datapb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datapb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Trace); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datapb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallRet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_datapb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_datapb_proto_goTypes,
		DependencyIndexes: file_datapb_proto_depIdxs,
		MessageInfos:      file_datapb_proto_msgTypes,
	}.Build()
	File_datapb_proto = out.File
	file_datapb_proto_rawDesc = nil
	file_datapb_proto_goTypes = nil
	file_datapb_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AgentClient is the client API for Agent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AgentClient interface {
	Request(ctx context.Context, in *RequestID, opts ...grpc.CallOption) (*CallRet, error)
}

type agentClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentClient(cc grpc.ClientConnInterface) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) Request(ctx context.Context, in *RequestID, opts ...grpc.CallOption) (*CallRet, error) {
	out := new(CallRet)
	err := c.cc.Invoke(ctx, "/datapb.Agent/Request", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServer is the server API for Agent service.
type AgentServer interface {
	Request(context.Context, *RequestID) (*CallRet, error)
}

// UnimplementedAgentServer can be embedded to have forward compatible implementations.
type UnimplementedAgentServer struct {
}

func (*UnimplementedAgentServer) Request(context.Context, *RequestID) (*CallRet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Request not implemented")
}

func RegisterAgentServer(s *grpc.Server, srv AgentServer) {
	s.RegisterService(&_Agent_serviceDesc, srv)
}

func _Agent_Request_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Request(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/datapb.Agent/Request",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Request(ctx, req.(*RequestID))
	}
	return interceptor(ctx, in, info, handler)
}

var _Agent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "datapb.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Request",
			Handler:    _Agent_Request_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "datapb.proto",
}

// CollectorClient is the client API for Collector service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CollectorClient interface {
	Report(ctx context.Context, in *Trace, opts ...grpc.CallOption) (*CallRet, error)
}

type collectorClient struct {
	cc grpc.ClientConnInterface
}

func NewCollectorClient(cc grpc.ClientConnInterface) CollectorClient {
	return &collectorClient{cc}
}

func (c *collectorClient) Report(ctx context.Context, in *Trace, opts ...grpc.CallOption) (*CallRet, error) {
	out := new(CallRet)
	err := c.cc.Invoke(ctx, "/datapb.Collector/Report", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CollectorServer is the server API for Collector service.
type CollectorServer interface {
	Report(context.Context, *Trace) (*CallRet, error)
}

// UnimplementedCollectorServer can be embedded to have forward compatible implementations.
type UnimplementedCollectorServer struct {
}

func (*UnimplementedCollectorServer) Report(context.Context, *Trace) (*CallRet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Report not implemented")
}

func RegisterCollectorServer(s *grpc.Server, srv CollectorServer) {
	s.RegisterService(&_Collector_serviceDesc, srv)
}

func _Collector_Report_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Trace)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorServer).Report(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/datapb.Collector/Report",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorServer).Report(ctx, req.(*Trace))
	}
	return interceptor(ctx, in, info, handler)
}

var _Collector_serviceDesc = grpc.ServiceDesc{
	ServiceName: "datapb.Collector",
	HandlerType: (*CollectorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Report",
			Handler:    _Collector_Report_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "datapb.proto",
}
