/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class simple */

#ifndef _Included_simple
#define _Included_simple
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     simple
 * Method:    TracerStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_simple_TracerStop
  (JNIEnv *, jobject);

/*
 * Class:     simple
 * Method:    TracerUpdate
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_simple_TracerUpdate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     simple
 * Method:    TracerSet
 * Signature: (JLjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_simple_TracerSet
  (JNIEnv *, jobject, jlong, jstring, jlong);

/*
 * Class:     simple
 * Method:    TracerGetCurrReq
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_simple_TracerGetCurrReq
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
